kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: polaris-testbed
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /Users/nkratky/Desktop/polaris-disks/control-plane/
        containerPath: /polaris-disks
  - role: worker
    extraMounts:
      - hostPath: /Users/nkratky/Desktop/polaris-disks/worker1/
        containerPath: /polaris-disks
  - role: worker
    extraMounts:
      - hostPath: /Users/nkratky/Desktop/polaris-disks/worker2/
        containerPath: /polaris-disks
